### ISSUE TITLE
option UCI_LimitStrength set to True make limiting the nps to 100000

### ISSUE THREAD

**Issue by BrennusJ** [peterosterlund2/texel#1]
i'm using texel under Lichess - i catch the opponent ELO to set it in parameters before start the game
I don't understand the goal to limit nps arround 200000 when UCI_LimitStrength  is set to true what ever if the UCI_Elo value is set to 2540 (maximum value possible)
2540 is the max possible value for UCI_Elo, so set from this value the nps should not be limited
i suggest is UCI_Elo is set over 2540 to unlimit any nps restriction
Any way the MaxNPS option is a very a usefull thing
an direct option to limit the ELO only limiting the nps will be very usefull
on Lichess 50 nps give 1750 ELO

**Comment by peterosterlund2** [comment]
The reason to limit NPS is that I want the UCI_Elo setting to work the same regardless of the actual speed of the CPU (within reason). The program can of course play stronger than 2540, but there is no controlled way to specify strengths larger than 2540. You would have to set "Strength" and/or "MaxNPS" manually for that, and the result may depend on the CPU speed (if MaxNPS is not set or set higher than the CPU can deliver.)
