### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by BrennusJ** [peterosterlund2/texel#3]
Hello,

I don't understand : the current version i use on lichess : [https://lichess.org/@/ELO_1500](url) is already 1.08a18 and seems to get already the change.
FYI : MaxNPS is a really great feature for me : it allowed to reduce  Strength saving CPU to be able to run more than one game on RaspBerry nanocomputer.
FYI : with limited 100 nps, mainly against other bot on  Lichess the ELO is around 1750 all other setting hash, TB, book set to what i think the best

Peter, Thanks you for great work on Texel

no NNUE evaluation on sight ?

**Comment by peterosterlund2** [comment]
Hi,

The version number scheme I use is non-standard. The "a" means alpha, i.e. a not feature-complete version. So all the 1.08aX versions precede the 1.08 version.

No NNUE evaluation planned for now.
